#!/usr/bin/env python3
"""Generate assets/winsend.ico.

The icon is drawn here rather than committed as an opaque binary someone would
have to open an editor to change. Pure standard library on purpose: an icon
that can only be regenerated by first installing an imaging package is an icon
that stops being regenerated.

Run from the repository root:

    python3 tools/make_icon.py

Pass --preview to also write a PNG next to the .ico for eyeballing, since a
32x32 tray icon is hard to judge from its pixel values.
"""

import argparse
import struct
import zlib
from pathlib import Path

# Matches ACCENT in src/app.rs, so the tray icon and the Send button are
# recognisably the same application.
ACCENT = (78, 142, 240)
WHITE = (255, 255, 255)
STAND = (150, 178, 226)

SIZES = (16, 32, 48)
# The window and taskbar icon is handed to eframe as raw pixels, so it is
# written out already decoded. A .ico would mean parsing a container at startup
# to recover exactly this.
RGBA_SIZE = 64
# Every shape is drawn at this multiple and box-filtered down, which is the
# whole of the antialiasing strategy.
SUPERSAMPLE = 8


def rounded_rect(x0, y0, x1, y1, radius):
    """Coverage test for a rounded rectangle in normalised coordinates."""

    def inside(x, y):
        if not (x0 <= x <= x1 and y0 <= y <= y1):
            return False
        # Only the four corner boxes need the distance check.
        cx = x0 + radius if x < x0 + radius else (x1 - radius if x > x1 - radius else x)
        cy = y0 + radius if y < y0 + radius else (y1 - radius if y > y1 - radius else y)
        if cx == x and cy == y:
            return True
        return (x - cx) ** 2 + (y - cy) ** 2 <= radius**2

    return inside


def rect(x0, y0, x1, y1):
    return lambda x, y: x0 <= x <= x1 and y0 <= y <= y1


def triangle(ax, ay, bx, by, cx, cy):
    """Coverage test for a triangle, by consistent edge sign."""

    def side(px, py, qx, qy, rx, ry):
        return (qx - px) * (ry - py) - (qy - py) * (rx - px)

    def inside(x, y):
        d1 = side(ax, ay, bx, by, x, y)
        d2 = side(bx, by, cx, cy, x, y)
        d3 = side(cx, cy, ax, ay, x, y)
        return not ((d1 < 0 or d2 < 0 or d3 < 0) and (d1 > 0 or d2 > 0 or d3 > 0))

    return inside


# A monitor with an arrow entering it: the whole application in one glyph.
# Normalised so a single description serves every size.
SCREEN = rounded_rect(0.06, 0.12, 0.94, 0.72, 0.10)
NECK = rect(0.42, 0.72, 0.58, 0.84)
BASE = rounded_rect(0.26, 0.84, 0.74, 0.93, 0.045)
SHAFT = rect(0.22, 0.36, 0.56, 0.48)
HEAD = triangle(0.52, 0.24, 0.52, 0.60, 0.78, 0.42)


def sample(x, y):
    """Colour at a point, or None where the icon is transparent."""
    if SHAFT(x, y) or HEAD(x, y):
        # The arrow only shows where there is a screen behind it.
        return WHITE if SCREEN(x, y) else None
    if SCREEN(x, y):
        return ACCENT
    if NECK(x, y) or BASE(x, y):
        return STAND
    return None


def render(size):
    """Supersampled BGRA rows, top-down."""
    pixels = []
    step = SUPERSAMPLE * SUPERSAMPLE
    for py in range(size):
        row = []
        for px in range(size):
            r = g = b = a = 0
            for sy in range(SUPERSAMPLE):
                for sx in range(SUPERSAMPLE):
                    x = (px + (sx + 0.5) / SUPERSAMPLE) / size
                    y = (py + (sy + 0.5) / SUPERSAMPLE) / size
                    colour = sample(x, y)
                    if colour is not None:
                        r += colour[0]
                        g += colour[1]
                        b += colour[2]
                        a += 255
            if a == 0:
                row.append((0, 0, 0, 0))
                continue
            # Weight colour by covered samples only, so edges do not darken
            # towards the transparent background.
            covered = a // 255
            row.append((r // covered, g // covered, b // covered, a // step))
        pixels.append(row)
    return pixels


def ico_image(pixels):
    """One ICO entry: a BITMAPINFOHEADER, a bottom-up BGRA image, and the AND
    mask that pre-alpha Windows still expects to be present."""
    size = len(pixels)
    header = struct.pack(
        "<IiiHHIIiiII",
        40,          # biSize
        size,        # biWidth
        size * 2,    # biHeight, doubled to cover the AND mask
        1,           # biPlanes
        32,          # biBitCount
        0,           # biCompression, BI_RGB
        0,           # biSizeImage
        0, 0, 0, 0,  # resolution and palette counts
    )

    colour = bytearray()
    for row in reversed(pixels):
        for r, g, b, a in row:
            colour += bytes((b, g, r, a))

    # 1 bit per pixel, rows padded to four bytes. Fully transparent where the
    # alpha channel is, which modern Windows ignores and older paths do not.
    mask_stride = ((size + 31) // 32) * 4
    mask = bytearray()
    for row in reversed(pixels):
        bits = bytearray(mask_stride)
        for x, (_, _, _, a) in enumerate(row):
            if a == 0:
                bits[x // 8] |= 0x80 >> (x % 8)
        mask += bits

    return header + bytes(colour) + bytes(mask)


def write_ico(path):
    images = [ico_image(render(size)) for size in SIZES]

    offset = 6 + 16 * len(images)
    directory = bytearray(struct.pack("<HHH", 0, 1, len(images)))
    for size, image in zip(SIZES, images):
        directory += struct.pack(
            "<BBBBHHII", size, size, 0, 0, 1, 32, len(image), offset
        )
        offset += len(image)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(directory) + b"".join(images))
    return path


def write_rgba(path, size):
    """Raw RGBA rows, top-down, no header.

    The consumer is eframe's window icon, which wants exactly this. Keeping it
    headerless means the Rust side is an include_bytes! and two constants
    rather than an image decoder pulled in for one 64-pixel square.
    """
    raw = bytearray()
    for row in render(size):
        for r, g, b, a in row:
            raw += bytes((r, g, b, a))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(raw))
    return path


def write_png(path, size):
    """Preview only. Never embedded; the .ico is what ships."""
    pixels = render(size)
    raw = bytearray()
    for row in pixels:
        raw += b"\x00"
        for r, g, b, a in row:
            raw += bytes((r, g, b, a))

    def chunk(kind, payload):
        return (
            struct.pack(">I", len(payload))
            + kind
            + payload
            + struct.pack(">I", zlib.crc32(kind + payload))
        )

    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(bytes(raw)))
        + chunk(b"IEND", b"")
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", type=Path, help="also write a PNG here")
    parser.add_argument("--preview-size", type=int, default=128)
    args = parser.parse_args()

    written = write_ico(Path("assets/winsend.ico"))
    print(f"wrote {written} ({written.stat().st_size} bytes)")

    rgba = write_rgba(Path(f"assets/winsend-{RGBA_SIZE}.rgba"), RGBA_SIZE)
    print(f"wrote {rgba} ({rgba.stat().st_size} bytes)")

    if args.preview:
        write_png(args.preview, args.preview_size)
        print(f"wrote {args.preview}")
